---
- name: Mac Setup to osx-default
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#local-playbooks
  hosts: 127.0.0.1
  connection: local
  # https://docs.ansible.com/ansible/latest/user_guide/become.html#id1
  # become: yes
  tasks:
    - name: Setting MacOS finder
      osx_defaults: >
        domain={{ item.domain }}
        key={{ item.key }}
        type={{ item.type }}
        value={{ item.value }}
      with_items:
        - { domain: com.apple.finder, key: CreateDesctop, type: bool, value: false }
        - { domain: com.apple.finder, key: AppleShowAllFiles, type: bool, value: true }

    - name: Setting MacOS systemuiserver
      osx_defaults:
        domain: com.apple.systemuiserver
        key: menuExtras
        type: array
        value:
          - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
          - "/System/Library/CoreServices/Menu Extras/Battery.menu"
          - "/System/Library/CoreServices/Menu Extras/Clock.menu"